program: main.py
method: bayes 
metric:
  name: val_loss
  goal: minimize
parameters:
  learning_rate:
    max: 0.01
    min: 0.0001
  batch_size:
    values: [32, 64, 128, 256, 512]
  warmup_epochs:
    min: 5
    max: 40
  backbone_name:
    values: ["LaNet"]
